### ISSUE TITLE
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.

### ISSUE THREAD

**Issue by alessandroferrari** [defeatcovid19/defeatcovid19-net-pytorch#4]
Hi,
steps to repro:

- setup conda env based on the yaml;
- downloaded dataset from Kaggle for pneumonia, copied under input/chest-xray-pneumonia
- downloaded dataset from Covid chestray, copied under input/covid_chestray

From input folder:
```
.
./.gitkeep
./chest-xray-pneumonia
./chest-xray-pneumonia/train
./chest-xray-pneumonia/chest_xray
./chest-xray-pneumonia/__MACOSX
./chest-xray-pneumonia/test
./chest-xray-pneumonia/val
./covid_chestxray
./covid_chestxray/README.md
./covid_chestxray/images
./covid_chestxray/docs
./covid_chestxray/metadata.csv
./covid_chestxray/.git
./covid_chestxray/CONTRIBUTING.md
./covid_chestxray/.~lock.metadata.csv#
./covid_chestxray/.gitignore
```

- run train.py script from conda env, with current default params.

```
`Python version: 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0]
NumPy version: 1.18.1
scikit-learn version: 0.22.1
pandas version: 1.0.3
OpenCV version: 4.2.0
Torch version: 1.4.0
Available GPUs: 1
Torch device: cuda
ChestXRayPneumoniaDataset initialized with size=256, augment=None
Dataset is located in input/chest-xray-pneumonia
Dataset:                                                   image label
0     input/chest-xray-pneumonia/train/NORMAL/NORMAL...     0
1     input/chest-xray-pneumonia/train/NORMAL/NORMAL...     0
2     input/chest-xray-pneumonia/train/NORMAL/NORMAL...     0
3     input/chest-xray-pneumonia/train/NORMAL/IM-051...     0
4     input/chest-xray-pneumonia/train/NORMAL/IM-035...     0
...                                                 ...   ...
5851  input/chest-xray-pneumonia/test/PNEUMONIA/pers...     1
5852  input/chest-xray-pneumonia/test/PNEUMONIA/pers...     1
5853  input/chest-xray-pneumonia/test/PNEUMONIA/pers...     1
5854  input/chest-xray-pneumonia/test/PNEUMONIA/pers...     1
5855  input/chest-xray-pneumonia/test/PNEUMONIA/pers...     1

[5856 rows x 2 columns]
Trainer started with classifier: Resnet34 dataset: <datasets.chest_xray_pneumonia_dataset.ChestXRayPneumoniaDataset object at 0x7f28dd548e90> batch size: 64
Train set: 4684
Validation set: 1172
Training with 74 mini-batches per epoch
Logging performance every 15 iter, smoothing every: 74 iter
SGD (
Parameter Group 0
    dampening: 0
    initial_lr: 0.01
    lr: 0.01
    momentum: 0.9
    nesterov: False
    weight_decay: 0.0001
)'
<torch.optim.lr_scheduler.StepLR object at 0x7f285c7c2450>'
BCELoss()'
[Accuracy(), <function roc_auc_score at 0x7f285c1af560>]'
                    |         VALID        |        TRAIN         |         
 lr     iter  epoch | loss    roc    acc   | loss    roc    acc   |  time   
------------------------------------------------------------------------------
0.010000    0   0.0 |                      | 0.911  0.269  0.391  |   1.66
0.010000   15   0.2 |                      | 0.370  0.961  0.828  |  13.05
0.010000   30   0.4 |                      | 0.144  1.000  0.938  |  24.79
0.010000   45   0.6 |                      | 0.160  0.984  0.953  |  37.48
0.010000   60   0.8 |                      | 0.085  1.000  0.984  |  49.68
0.010000   74   1.0 | 0.123* 1.000  0.950  | 0.278* 0.935  0.882  |  75.19
0.010000   75   1.0 |                      | 0.081  0.986  0.984  |  77.23
0.010000   90   1.2 |                      | 0.105  0.997  0.984  |  88.95
0.010000  105   1.4 |                      | 0.097  0.989  0.953  | 100.94
0.010000  120   1.6 |                      | 0.087  0.993  0.984  | 112.91
0.010000  135   1.8 |                      | 0.025  1.000  1.000  | 124.32
0.010000  148   2.0 | 0.079* 1.000  0.950  | 0.091* 0.995  0.975  | 148.05
COVIDChestXRayDataset initialized with size=256, augment=None
Dataset is located in input/covid_chestxray
Dataset:                                                  image  label
0    input/covid_chestxray/images/auntminnie-a-2020...   True
1    input/covid_chestxray/images/auntminnie-b-2020...   True
2    input/covid_chestxray/images/auntminnie-c-2020...   True
3    input/covid_chestxray/images/auntminnie-d-2020...   True
4    input/covid_chestxray/images/nejmc2001573_f1a....   True
..                                                 ...    ...
159  input/covid_chestxray/images/pneumocystis-jiro...  False
160  input/covid_chestxray/images/pneumocystis-jiro...  False
161  input/covid_chestxray/images/pneumocystis-jiro...  False
162  input/covid_chestxray/images/legionella-pneumo...  False
163  input/covid_chestxray/images/legionella-pneumo...  False

[164 rows x 2 columns]
Executing a 5-fold cross validation
===Split #1===
Trainer started with classifier: Resnet34 dataset: <datasets.covid_chestxray_dataset.COVIDChestXRayDataset object at 0x7f28cca6e490> batch size: 64
Train set: 131
Validation set: 33
Training with 3 mini-batches per epoch
Logging performance every 1 iter, smoothing every: 3 iter
SGD (
Parameter Group 0
    dampening: 0
    initial_lr: 0.01
    lr: 0.01
    momentum: 0.9
    nesterov: False
    weight_decay: 0.0001
)'
<torch.optim.lr_scheduler.StepLR object at 0x7f285c124b50>'
BCELoss()'
[Accuracy(), <function roc_auc_score at 0x7f285c1af560>]'
                    |         VALID        |        TRAIN         |         
 lr     iter  epoch | loss    roc    acc   | loss    roc    acc   |  time   
------------------------------------------------------------------------------
0.010000    0   0.3 |                      | 2.232  0.357  0.516  |   3.19
0.010000    1   0.7 |                      | 2.492  0.448  0.500  |   7.16
0.010000    2   1.0 |                      | 4.214  0.000  0.333  |   7.20
0.010000    3   1.0 | 1.190* 0.474  0.606  | 2.980* 0.268  0.450  |   8.29
0.010000    3   1.3 |                      | 1.330  0.586  0.609  |  11.71
0.010000    4   1.7 |                      | 1.933  0.442  0.578  |  15.22
Traceback (most recent call last):
  File "/home/alessandro/workspace/defeatcovid19-net-pytorch/train.py", line 34, in <module>
    trainer.run(max_epochs=15)
  File "/home/alessandro/workspace/defeatcovid19-net-pytorch/trainer/trainer.py", line 106, in run
    batch_acc, batch_roc = [i(labels.cpu(), preds.cpu()).item() for i in metrics]
  File "/home/alessandro/workspace/defeatcovid19-net-pytorch/trainer/trainer.py", line 106, in <listcomp>
    batch_acc, batch_roc = [i(labels.cpu(), preds.cpu()).item() for i in metrics]
  File "/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_ranking.py", line 390, in roc_auc_score
    sample_weight=sample_weight)
  File "/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_base.py", line 77, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_ranking.py", line 221, in _binary_roc_auc_score
    raise ValueError("Only one class present in y_true. ROC AUC score "
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.`
```

Similar issue also with dockerbuild (see pull request). Maybe is something related at current params on the script? Or maybe that cuda runtime on my driver is 10.2

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64       Driver Version: 440.64       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro RTX 5000...  Off  | 00000000:01:00.0  On |                  N/A |
| N/A   40C    P8    13W /  N/A |    878MiB / 16125MiB |      3%      Default |
+-------------------------------+----------------------+----------------------+
```

**Comment by thundo** [comment]
Hi @alessandroferrari ,
are you sure you are running the script with the built conda env?

Because in the env yaml
```
python=3.8.2=h191fe78_0
cudatoolkit=10.1.243=h6bb024c_0
pytorch=1.4.0=py3.8_cuda10.1.243_cudnn7.6.3_0
```
are specified, while in your logs I see python 3.7.4 and cuda 10.2. Maybe is it running with the system env?

**Comment by alessandroferrari** [comment]
Thanks for your answer, you are indeed right, I have posted the results of the docker container, from there the difference on python. I have similar results from the conda env, though, so i suspect the problem is somewhere else:

```
(defeatcovi19) alessandro@:~/workspace/defeatcovid19-net-pytorch$ python3 train.py 
Python version: 3.8.2 (default, Mar 25 2020, 17:03:02) 
[GCC 7.3.0]
NumPy version: 1.18.1
scikit-learn version: 0.22.1
pandas version: 1.0.3
OpenCV version: 4.2.0
Torch version: 1.4.0
Available GPUs: 1
Torch device: cuda
ChestXRayPneumoniaDataset initialized with size=256, augment=None
Dataset is located in input/chest-xray-pneumonia
Dataset:                                                   image label
0     input/chest-xray-pneumonia/train/NORMAL/NORMAL...     0
1     input/chest-xray-pneumonia/train/NORMAL/NORMAL...     0
2     input/chest-xray-pneumonia/train/NORMAL/NORMAL...     0
3     input/chest-xray-pneumonia/train/NORMAL/IM-051...     0
4     input/chest-xray-pneumonia/train/NORMAL/IM-035...     0
...                                                 ...   ...
5851  input/chest-xray-pneumonia/test/PNEUMONIA/pers...     1
5852  input/chest-xray-pneumonia/test/PNEUMONIA/pers...     1
5853  input/chest-xray-pneumonia/test/PNEUMONIA/pers...     1
5854  input/chest-xray-pneumonia/test/PNEUMONIA/pers...     1
5855  input/chest-xray-pneumonia/test/PNEUMONIA/pers...     1

[5856 rows x 2 columns]
Trainer started with classifier: Resnet34 dataset: <datasets.chest_xray_pneumonia_dataset.ChestXRayPneumoniaDataset object at 0x7f123f532d60> batch size: 64
Train set: 4684
Validation set: 1172
Training with 74 mini-batches per epoch
Logging performance every 15 iter, smoothing every: 74 iter
SGD (
Parameter Group 0
    dampening: 0
    initial_lr: 0.01
    lr: 0.01
    momentum: 0.9
    nesterov: False
    weight_decay: 0.0001
)'
<torch.optim.lr_scheduler.StepLR object at 0x7f11affff700>'
BCELoss()'
[Accuracy(), <function roc_auc_score at 0x7f11c8cac160>]'
                    |         VALID        |        TRAIN         |         
 lr     iter  epoch | loss    roc    acc   | loss    roc    acc   |  time   
------------------------------------------------------------------------------
0.010000    0   0.0 |                      | 0.825  0.357  0.438  |   1.33
0.010000   15   0.2 |                      | 0.509  0.987  0.812  |  10.63
0.010000   30   0.4 |                      | 0.268  0.964  0.906  |  20.01
0.010000   45   0.6 |                      | 0.145  1.000  0.938  |  29.47
0.010000   60   0.8 |                      | 0.136  0.986  0.953  |  39.47
0.010000   74   1.0 | 0.113* 1.000  1.000  | 0.267* 0.943  0.889  |  60.20
0.010000   75   1.0 |                      | 0.070  0.999  0.969  |  61.76
0.010000   90   1.2 |                      | 0.014  1.000  1.000  |  71.10
0.010000  105   1.4 |                      | 0.003  1.000  1.000  |  80.85
0.010000  120   1.6 |                      | 0.018  1.000  1.000  |  90.28
0.010000  135   1.8 |                      | 0.182  0.994  0.953  |  99.79
0.010000  148   2.0 | 0.137* 1.000  0.950  | 0.080* 0.996  0.977  | 118.48
COVIDChestXRayDataset initialized with size=256, augment=None
Dataset is located in input/covid_chestxray
Dataset:                                                  image  label
0    input/covid_chestxray/images/auntminnie-a-2020...   True
1    input/covid_chestxray/images/auntminnie-b-2020...   True
2    input/covid_chestxray/images/auntminnie-c-2020...   True
3    input/covid_chestxray/images/auntminnie-d-2020...   True
4    input/covid_chestxray/images/nejmc2001573_f1a....   True
..                                                 ...    ...
159  input/covid_chestxray/images/pneumocystis-jiro...  False
160  input/covid_chestxray/images/pneumocystis-jiro...  False
161  input/covid_chestxray/images/pneumocystis-jiro...  False
162  input/covid_chestxray/images/legionella-pneumo...  False
163  input/covid_chestxray/images/legionella-pneumo...  False

[164 rows x 2 columns]
Executing a 5-fold cross validation
===Split #1===
Trainer started with classifier: Resnet34 dataset: <datasets.covid_chestxray_dataset.COVIDChestXRayDataset object at 0x7f11c8b091c0> batch size: 64
Train set: 131
Validation set: 33
Training with 3 mini-batches per epoch
Logging performance every 1 iter, smoothing every: 3 iter
SGD (
Parameter Group 0
    dampening: 0
    initial_lr: 0.01
    lr: 0.01
    momentum: 0.9
    nesterov: False
    weight_decay: 0.0001
)'
<torch.optim.lr_scheduler.StepLR object at 0x7f11affc6fa0>'
BCELoss()'
[Accuracy(), <function roc_auc_score at 0x7f11c8cac160>]'
                    |         VALID        |        TRAIN         |         
 lr     iter  epoch | loss    roc    acc   | loss    roc    acc   |  time   
------------------------------------------------------------------------------
0.010000    0   0.3 |                      | 2.044  0.536  0.562  |   3.76
0.010000    1   0.7 |                      | 2.084  0.503  0.578  |   6.56
0.010000    2   1.0 |                      | 0.017  1.000  1.000  |   6.59
0.010000    3   1.0 | 1.685* 0.430  0.697  | 1.382* 0.680  0.714  |   7.55
0.010000    3   1.3 |                      | 1.770  0.573  0.562  |  11.23
0.010000    4   1.7 |                      | 1.171  0.677  0.641  |  14.07
0.010000    5   2.0 |                      | 0.414  1.000  0.667  |  14.10
0.010000    6   2.0 | 1.507* 0.417  0.667  | 1.118* 0.750  0.623  |  15.04
0.009000    6   2.3 |                      | 1.015  0.753  0.734  |  18.44
0.009000    7   2.7 |                      | 0.447  0.869  0.828  |  21.26
Traceback (most recent call last):
  File "train.py", line 34, in <module>
    trainer.run(max_epochs=15)
  File "/home/alessandro/workspace/defeatcovid19-net-pytorch/trainer/trainer.py", line 106, in run
    batch_acc, batch_roc = [i(labels.cpu(), preds.cpu()).item() for i in metrics]
  File "/home/alessandro/workspace/defeatcovid19-net-pytorch/trainer/trainer.py", line 106, in <listcomp>
    batch_acc, batch_roc = [i(labels.cpu(), preds.cpu()).item() for i in metrics]
  File "/home/alessandro/anaconda3/envs/defeatcovi19/lib/python3.8/site-packages/sklearn/metrics/_ranking.py", line 387, in roc_auc_score
    return _average_binary_score(partial(_binary_roc_auc_score,
  File "/home/alessandro/anaconda3/envs/defeatcovi19/lib/python3.8/site-packages/sklearn/metrics/_base.py", line 77, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "/home/alessandro/anaconda3/envs/defeatcovi19/lib/python3.8/site-packages/sklearn/metrics/_ranking.py", line 221, in _binary_roc_auc_score
    raise ValueError("Only one class present in y_true. ROC AUC score "
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
```
In the next days when I have some time to look at it with more detail i will look into this! thanks for your effort

**Comment by mrtj** [comment]
Hello, I think this error due that some of the [positive; negative] labels are not finished in a particular batch. The COVID training set is rather small, 180 samples consisting of 128 positive and 52 negative cases. These are subdivided in training (80%) and validation set (20%) in a stratified way during the cross-validation. This means that there will be approximately 41 negative  out of 144 total cases in the training set. The default batch size is set to 64 for this training but among the 144 ( = 64 + 64 + 16) samples the length of the last batch will be only 16. As the data points are selected randomly for the batch, there is a small but non zero ( (1 - 41/144)^16 ~ 0.5%) probability that there will be no negative label in the last, small batch.

**Comment by mrtj** [comment]
An alternative fix could be to calculate the metrics only once per epoch, on the full training / validation set. What do you think @thundo?

**Comment by thundo** [comment]
One per epoch seems a much better option.

**Comment by alessandroferrari** [comment]
The issue is that the training set has 131 images, with a batch of 64, the third batch will be only 3 images, with a large likelihood that there is not a sampling for all the labels. It may actually even be harmfull for the net to get gradients from such a noisy batch. My recommendation would be to set the drop_last to False in the training set dataloader, I am preparing a PR that will fix this soon, so that you can merge if you think it helps.
